version: "2"

services:
  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget
    ports:
      - "6789:6789"
    volumes:
      - /dockerfs/nzbget/config:/config
      - /dockerfs/nzbget/config:/downloads
      - /mnt/media/downloads:/downloads_actual
    env_file: env
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    ports:
      - "8989:8989"
    volumes:
      - /dockerfs/sonarr/config:/config
      - /mnt/media:/media
      - /dev/rtc:/dev/rtc:ro
      - /mnt/media/downloads:/downloads_actual
    env_file: env
    restart: unless-stopped

  couchpotato:
    container_name: couchpotato
    image: linuxserver/couchpotato
    ports:
      - "5050:5050"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dockerfs/couchpotato/config:/config
      - /mnt/media/downloads:/downloads
      - /mnt/media/movies:/movies
    env_file: env
    restart: unless-stopped

  plexpy:
    container_name: plexpy
    image: linuxserver/plexpy
    ports:
      - "8181:8181"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dockerfs/plexpy/config:/config
      - /mnt/plex_logs:/logs:ro
    env_file: env
    restart: unless-stopped

  deluge:
    container_name: deluge
    image: linuxserver/deluge
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dockerfs/deluge/config:/config
      - /mnt/media/downloads:/media/downloads
    env_file: env
    network_mode: host
    restart: unless-stopped

  consul:
    container_name: consul
    image: gliderlabs/consul-server
    network_mode: host
    command: -bind 192.168.239.6 -bootstrap
    restart: unless-stopped

  registrator:
    container_name: registrator
    image: gliderlabs/registrator
    network_mode: host
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: consul://localhost:8500
    restart: unless-stopped

  owncloud_db:
    container_name: owncloud_db
    image: mariadb
    volumes:
      - /dockerfs/owncloud_db/data:/var/lib/mysql
      - /dockerfs/owncloud_db/config:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=owncloud
      - MYSQL_USER=owncloud
    env_file:
      - owncloud_db_secrets.env
    restart: unless-stopped

  owncloud:
    container_name: owncloud
    image: owncloud:9.0.2
    volumes:
      - /dockerfs/owncloud/apps:/var/www/html/apps
      - /dockerfs/owncloud/config:/var/www/html/config
      - /mnt/owncloud:/var/www/html/data
    ports:
      - "8080:80"
    links:
      - "owncloud_db"
    restart: unless-stopped
