version: "2"

services:
  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget
    ports:
      - "6789:6789"
    volumes:
      - /dockerfs/nzbget/config:/config
      - /dockerfs/nzbget/config:/downloads
      - /mnt/media/downloads:/downloads_actual
    env_file: env
    restart: always

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    ports:
      - "8989:8989"
    volumes:
      - /dockerfs/sonarr/config:/config
      - /mnt/media:/media
      - /dev/rtc:/dev/rtc:ro
      - /mnt/media/downloads:/downloads_actual
    env_file: env
    restart: always

  couchpotato:
    container_name: couchpotato
    image: linuxserver/couchpotato
    ports:
      - "5050:5050"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dockerfs/couchpotato/config:/config
      - /mnt/media/downloads:/downloads
      - /mnt/media/movies:/movies
    env_file: env
    restart: always

  plexpy:
    container_name: plexpy
    image: linuxserver/plexpy
    ports:
      - "8181:8181"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dockerfs/plexpy/config:/config
      - /mnt/plex_logs:/logs:ro
    env_file: env
    restart: always

  deluge:
    container_name: deluge
    image: linuxserver/deluge
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dockerfs/deluge/config:/config
      - /mnt/media/downloads:/media/downloads
    env_file: env
    network_mode: host
    restart: always

  consul:
    container_name: consul
    image: gliderlabs/consul-server
    network_mode: host
    command: -bind 192.168.239.6 -bootstrap
    restart: always

  registrator:
    container_name: registrator
    image: gliderlabs/registrator:v6
    network_mode: host
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: consul://localhost:8500
    restart: always

  owncloud_db:
    container_name: owncloud_db
    image: mariadb
    volumes:
      - /dockerfs/owncloud_db/data:/var/lib/mysql
      - /dockerfs/owncloud_db/config:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=owncloud
      - MYSQL_USER=owncloud
    env_file:
      - owncloud_db_secrets.env
    restart: always

  owncloud:
    container_name: owncloud
    image: wonderfall/nextcloud
    environment:
      - UID=1001
      - GID=1001
    volumes:
      - /mnt/owncloud:/data
      - /dockerfs/owncloud/config:/config
      - /dockerfs/owncloud/apps:/apps2
    ports:
      - "8080:80"
    links:
      - "owncloud_db"
    restart: always

  syncthing_discovery:
    container_name: syncthing_discovery
    image: syncthing_discovery
    ports:
      - "8443:8443"
    restart: always
    command: -http

  syncthing:
    container_name: syncthing
    image: linuxserver/syncthing
    network_mode: host
    env_file: env
    volumes:
      - /dockerfs/syncthing/config:/config
      - /mnt/syncthing:/mnt/syncthing
    restart: always

