version: "2"

networks:
  default:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      driver: default
      config:
        - subnet: 192.168.240.0/24
          ip_range: 192.168.240.0/25
          gateway: 192.168.240.1

services:
  consul:
    container_name: consul
    image: consul
    volumes:
      - /dockerfs/consul/data:/consul/data
      - /dockerfs/consul/config:/consul/config
    command: consul agent -server -client=0.0.0.0 -bootstrap-expect=1 -data-dir /consul/data -ui
    restart: always
    read_only: true
    tmpfs:
      - /run
      - /tmp
    networks:
      default:
        ipv4_address: 192.168.240.128

  registrator:
    container_name: registrator
    image: gliderlabs/registrator
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: -internal -resync 60 consul://consul:8500
    restart: always
    read_only: true
    tmpfs:
      - /run
      - /tmp
    depends_on:
      - consul

  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget
    ports:
      - "6789"
    volumes:
      - /dockerfs/nzbget/config:/config
      - /dockerfs/nzbget/config:/downloads
      - /net/freenas.radoncanyon.com/mnt/etank/media/downloads:/downloads_actual
    env_file: env/common
    restart: always

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    ports:
      - "8989"
    volumes:
      - /dockerfs/sonarr/config:/config
      - /net/freenas.radoncanyon.com/mnt/etank/media:/media
      - /dev/rtc:/dev/rtc:ro
      - /net/freenas.radoncanyon.com/mnt/etank/media/downloads:/downloads_actual
    env_file: env/common
    restart: always

  couchpotato:
    container_name: couchpotato
    image: linuxserver/couchpotato
    ports:
      - "5050"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dockerfs/couchpotato/config:/config
      - /net/freenas.radoncanyon.com/mnt/etank/media/downloads:/downloads_actual
      - /net/freenas.radoncanyon.com/mnt/etank/media/movies:/movies
    env_file: env/common
    restart: always

  plexpy:
    container_name: plexpy
    image: linuxserver/plexpy
    ports:
      - "8181"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dockerfs/plexpy/config:/config
      - /mnt/plex_logs:/logs:ro
    env_file: env/common
    restart: always

  pritunl:
    container_name: pritunl
    image: michelkaeser/docker-pritunl
    ports:
      - "443"
    environment:
      # http://gliderlabs.com/registrator/latest/user/services/#container-overrides
      - SERVICE_NAME=pritunl
    volumes:
      - /dockerfs/pritunl/pritunl:/var/lib/pritunl
      - /dockerfs/pritunl/mongodb:/var/lib/mongodb
    networks:
      default:
        ipv4_address: 192.168.240.129
    privileged: true
    restart: always

  unifi:
    container_name: unifi
    image: linuxserver/unifi
    env_file: env/common
    ports:
      - "8080"
      - "8081"
      - "8443"
      - "8843"
      - "8880"
    volumes:
      - /dockerfs/unifi/config:/config
    restart: always
    networks:
      default:
        ipv4_address: 192.168.240.130

  deluge:
    container_name: deluge
    image: linuxserver/deluge
    ports:
      - "8112"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dockerfs/deluge/config:/config
      - /net/freenas.radoncanyon.com/mnt/etank/media/downloads:/media/downloads
    env_file: env/common
    restart: always
    networks:
      default:
        ipv4_address: 192.168.240.131

  jenkins:
    container_name: jenkins
    image: jenkins:alpine
    ports:
      - "8080"
    volumes:
      - "/dockerfs/jenkins/data:/var/jenkins_home"
    restart: always
    read_only: true
    tmpfs:
      - /tmp
      - /run

  oauth2_proxy:
    container_name: oauth2_proxy
    image: zappi/oauth2_proxy
    env_file: env/private/oauth2_proxy
    volumes:
      - /dockerfs/oauth2_proxy/config:/etc/oauth2_proxy:ro
    command: >
      --upstream="file:///dev/null"
      --http-address="0.0.0.0:4180"
      --cookie-refresh="1h"
      --cookie-domain=".desertbluffs.com"
      --cookie-secure=true
      --cookie-httponly=true
      --authenticated-emails-file="/etc/oauth2_proxy/authenticated_emails"
    restart: always
    read_only: true
    tmpfs:
      - /run
      - /tmp
    networks:
      default:
        ipv4_address: 192.168.240.136

  gitea:
    container_name: gitea
    image: gitea/gitea
    ports:
      - "3000"
    volumes:
      - /dockerfs/gitea/data:/data
    restart: always
    tmpfs:
      - /run
      - /tmp
    networks:
      default:
        ipv4_address: 192.168.240.137

  gitea-mysql:
    container_name: gitea-mysql
    image: mysql
    volumes:
      - /dockerfs/gitea-mysql/data:/var/lib/mysql
    env_file: 
      - env/gitea-mysql
      - env/private/gitea-mysql
    command: mysqld --pid-file /var/lib/mysql/mysqld.pid --socket /var/lib/mysql/mysqld.sock
    restart: always
    read_only: true
    tmpfs:
      - /tmp
      - /run
