nzbget:
  container_name: nzbget
  image: linuxserver/nzbget
  ports:
  - "6789:6789"
  volumes:
  - /dockerfs/nzbget/config:/config
  - /dockerfs/nzbget/config:/downloads
  - /media/downloads:/downloads_actual
  env_file: env

sonarr:
  container_name: sonarr
  image: linuxserver/sonarr
  ports:
  - "8989:8989"
  volumes:
  - /dockerfs/sonarr/config:/config
  - /media:/media
  - /dev/rtc:/dev/rtc:ro
  - /media/downloads:/downloads_actual
  env_file: env

couchpotato:
  container_name: couchpotato
  image: linuxserver/couchpotato
  ports:
  - "5050:5050"
  volumes:
  - /etc/localtime:/etc/localtime:ro
  - /dockerfs/couchpotato/config:/config
  - /media/downloads:/downloads
  - /media/movies:/movies
  env_file: env

plexpy:
  container_name: plexpy
  image: linuxserver/plexpy
  ports:
  - "8181:8181"
  volumes:
  - /etc/localtime:/etc/localtime:ro
  - /dockerfs/plexpy/config:/config
  env_file: env

deluge:
  container_name: deluge
  image: linuxserver/deluge
  volumes:
  - /etc/localtime:/etc/localtime:ro
  - /dockerfs/deluge/config:/config
  - /media/downloads:/media/downloads
  env_file: env
  net: host

consul:
  container_name: consul
  image: gliderlabs/consul-server
  net: host
  command: -bind 192.168.239.6 -bootstrap

registrator:
  container_name: registrator
  image: gliderlabs/registrator
  net: host
  volumes:
  - /var/run/docker.sock:/tmp/docker.sock
  command: consul://localhost:8500
