version: "2"

networks:
  default:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      driver: default
      config:
        - subnet: 192.168.240.0/24
          ip_range: 192.168.240.0/25
          gateway: 192.168.240.1

services:
  consul:
    container_name: consul
    image: gliderlabs/consul-server:latest
    command: -bootstrap
    restart: always
    networks:
      default:
        ipv4_address: 192.168.240.128

  registrator:
    container_name: registrator
    image: gliderlabs/registrator:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: -internal consul://consul:8500
    restart: always
    depends_on:
      - consul

  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget
    ports:
      - "6789"
    volumes:
      - /dockerfs/nzbget/config:/config
      - /dockerfs/nzbget/config:/downloads
      - /mnt/media/downloads:/downloads_actual
    env_file: env
    restart: always

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    ports:
      - "8989"
    volumes:
      - /dockerfs/sonarr/config:/config
      - /mnt/media:/media
      - /dev/rtc:/dev/rtc:ro
      - /mnt/media/downloads:/downloads_actual
    env_file: env
    restart: always

  couchpotato:
    container_name: couchpotato
    image: linuxserver/couchpotato
    ports:
      - "5050"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dockerfs/couchpotato/config:/config
      - /mnt/media/downloads:/downloads
      - /mnt/media/movies:/movies
    env_file: env
    restart: always

  plexpy:
    container_name: plexpy
    image: linuxserver/plexpy
    ports:
      - "8181"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dockerfs/plexpy/config:/config
      - /mnt/plex_logs:/logs:ro
    env_file: env
    restart: always

  deluge:
    container_name: deluge
    image: linuxserver/deluge
    ports:
      - "8112"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dockerfs/deluge/config:/config
      - /mnt/media/downloads:/media/downloads
    env_file: env
    restart: always

  syncthing:
    container_name: syncthing
    image: linuxserver/syncthing
    env_file: env
    ports:
      - "8384"
    volumes:
      - /dockerfs/syncthing/config:/config
      - /mnt/syncthing:/mnt/syncthing
    restart: always

  pritunl:
    container_name: pritunl
    image: michelkaeser/docker-pritunl
    privileged: true
    ports:
      - "443"
      - "1194"
      - "1194/udp"
    restart: always

