version: '2.1'

networks:

  physical:
    external:
      name: wedge_physical

services:

  plex:
    image: plexinc/pms-docker
    container_name: plex
    volumes:
      - /mnt/media:/media:ro
      - /dockerfs/pms/config:/config
      - /dockerfs/pms/transcode:/transcode'
    environment:
      - 'TZ=America/New_York'
      - 'PLEX_UID=1001'
      - 'PLEX_GID=1001'
    networks:
      physical:
        ipv4_address: 192.168.227.255

  plexpy:
    image: linuxserver/plexpy
    container_name: plexpy
    volumes:
      - /dockerfs/plexpy/config:/config
      - '/dockerfs/pms/config/Library/Application Support/Plex Media Server/Logs/:/logs:ro'
    ports:
      - "8181:8181/tcp"
    environment:
      - 'PUID=1001'
      - 'PGID=1001'
      - 'TZ=America/New_York'
    networks:
      physical:
