version: '2.1'

networks:

  physical:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      driver: default
      config:
        - subnet: 192.168.240.0/24
          gateway: 192.168.240.1

services:

  plex:
    image: plexinc/pms-docker
    container_name: plex
    volumes:
      - /mnt/media:/media:ro
      - /dockerfs/pms/config:/config
      - /dockerfs/pms/transcode:/transcode'
    environment:
      - 'HOSTNAME=notzot'
      - 'TZ=America/New_York'
      - 'PLEX_UID=1001'
      - 'PLEX_GID=1001'
      - 'ALLOWED_NETWORKS=192.168.239.0/24,192.168.240.0/24'
    networks:
      physical:
        ipv4_address: 192.168.240.2
