version: '2.1'

networks:

  physical:
    external:
      name: cecil_physical

services:

  pritunl:
    image: michelkaeser/docker-pritunl
    container_name: pritunl
    volumes:
      - /dockerfs/pritunl/pritunl:/var/lib/pritunl
      - /dockerfs/pritunl/mongodb:/var/lib/mongodb
    networks:
      physical:
        ipv4_address: 192.168.226.255
    privileged: true
