version: '2.1'

networks:

  default:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      driver: default
      config:
        - ip_range: 192.168.226.0/24
          subnet: 192.168.224.0/19
          gateway: 192.168.224.1

services:

  consul:
    image: consul
    container_name: consul
    command: >-
      consul agent
      -server
      -retry-join=192.168.225.0
      -retry-join=192.168.226.0
      -retry-join=192.168.227.0
      -bootstrap-expect=3
      -data-dir /consul/data
      -node=cecil
      -client=0.0.0.0
      -ui
    environment:
      - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}'
    volumes:
      - /dockerfs/consul/config:/consul/config
      - /dockerfs/consul/data:/consul/data
    healthcheck:
      test: "curl --fail localhost:8500/v1/agent/self || exit 1"
    networks:
      default:
        ipv4_address: 192.168.226.0


  registrator:
    image: gliderlabs/registrator
    container_name: registrator
    command: >-
      -retry-attempts=-1
      -ttl=30
      -ttl-refresh=10
      -resync=60
      -cleanup
      -internal
      consul://consul:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      consul:
        condition: service_healthy

  traefik:
    image: traefik
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dockerfs/traefik/config:/etc/traefik
      - /dockerfs/traefik/config/acme/acme.json:/acme.json
    command: >-
      traefik
      --web
      --debug
      --configfile=/etc/traefik/traefik.toml
    env_file:
      - env/private/aws
    networks:
      default:
        ipv4_address: 192.168.226.254
    ports:
      - '80'
      - '443'
      - '8080'
    environment:
      - 'SERVICE_80_NAME=traefik'
      - 'SERVICE_443_NAME=traefik'
      - 'SERVICE_8080_NAME=traefik'

  pritunl:
    image: michelkaeser/docker-pritunl
    container_name: pritunl
    volumes:
      - /dockerfs/pritunl/pritunl:/var/lib/pritunl
      - /dockerfs/pritunl/mongodb:/var/lib/mongodb
    privileged: true
    ports:
      - '443'
    environment:
      - 'SERVICE_NAME=pritunl'
      - 'SERVICE_TAGS=traefik.protocol=https,traefik.tags=production'
    networks:
      default:
        ipv4_address: 192.168.226.255

