version: '2.1'

networks:
  default:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      driver: default
      config:
        - ip_range: 172.16.9.0/24
          subnet: 172.16.8.0/22
          gateway: 172.16.8.1
    
services:
  consul:
    container_name: consul
    image: consul
    volumes:
      - /dockerfs/consul/data:/consul/data
      - /dockerfs/consul/config:/consul/config
    command: >-
      consul agent 
      -server 
      -client=0.0.0.0
      -bootstrap-expect=3 
      -data-dir=/consul/data 
      -ui
      -datacenter=radoncanyon
      -node=cecil
      -retry-join=172.16.9.0
      -retry-join=172.16.10.0
      -retry-join=172.16.11.0
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /run
      - /tmp
    networks:
      default: 
        ipv4_address: 172.16.9.0

  registrator:
    container_name: registrator
    image: gliderlabs/registrator
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    command: -internal -resync 60 consul://consul:8500
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /run
      - /tmp
    depends_on:
      - consul

  traefik:
    container_name: traefik
    image: traefik
    command: traefik --consul --consul.endpoint=consul:8500
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /run
      - /tmp
    depends_on:
      - consul
    ports:
      - "80:80/tcp"
      - "8080:8080/tcp"
    
