version: '2.1'

networks:

  default:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      driver: default
      config:
        - ip_range: 192.168.225.0/24
          subnet: 192.168.224.0/19
          gateway: 192.168.224.1

services:

  consul:
    image: consul
    container_name: consul
    command: >-
      consul agent
      -server
      -retry-join=192.168.225.255
      -retry-join=192.168.226.255
      -retry-join=192.168.227.255
      -bootstrap-expect=3
      -data-dir /consul/data
      -node=biggs
      -client=0.0.0.0
      -ui
    environment:
      - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}'
    volumes:
      - /dockerfs/consul/config:/consul/config
      - /dockerfs/consul/data:/consul/data
    healthcheck:
      test: "curl --fail localhost:8500/v1/agent/self || exit 1"
    networks:
      default:
        ipv4_address: 192.168.225.255
    restart: unless-stopped

  registrator:
    image: gliderlabs/registrator
    container_name: registrator
    command: >-
      -retry-attempts=-1
      -ttl=30
      -ttl-refresh=10
      -resync=60
      -cleanup
      -internal
      consul://consul:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      consul:
        condition: service_healthy
    restart: unless-stopped

  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    volumes:
      - /dockerfs/nzbget/config:/config
      - /mnt/downloads:/downloads
    environment:
      - 'TZ=America/New_York'
      - 'PUID=1001'
      - 'PGID=1001'
      - 'SERVICE_TAGS=traefik.tags=production'
    ports:
      - '6789'
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    volumes:
      - /dockerfs/sonarr/config:/config
      - /mnt/downloads:/downloads
      - /mnt/media:/media
      - /dev/rtc:/dev/rtc:ro
    environment:
      - 'PUID=1001'
      - 'PGID=1001'
      - 'SERVICE_TAGS=traefik.tags=production'
    ports:
      - '8989'
    restart: unless-stopped

  couchpotato:
    image: linuxserver/couchpotato
    container_name: couchpotato
    volumes:
      - /dockerfs/couchpotato/config:/config
      - /mnt/downloads:/downloads
      - /mnt/media/movies:/movies
    environment:
      - 'PUID=1001'
      - 'PGID=1001'
      - 'SERVICE_TAGS=traefik.tags=production'
    ports:
      - '5050'
    restart: unless-stopped

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    ports:
      - '8080'
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - /dockerfs/grafana/data
    environment:
      - 'SERVICE_TAGS=traefik.tags=production'
    ports:
      - '3000'
    restart: unless-stopped

  graphite-exporter:
    image: prom/graphite-exporter
    container_name: graphite-exporter
    command: >-
      -graphite.listen-address=":2003"
      -graphite.mapping-config=/tmp/graphite_mapping.conf
    volumes:
      - /dockerfs/graphite-exporter/config/graphite_mapping.conf:/tmp/graphite_mapping.conf:ro
    environment:
      - 'SERVICE_9108_NAME=graphite-exporter'
      - 'SERVICE_2003_NAME=graphite-exporter'
    ports:
      - '9108'
      - '2003'
      - '2003/udp'
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - /dockerfs/prometheus/data:/prometheus
      - /dockerfs/prometheus/config:/etc/prometheus
    ports:
      - '9090'
    restart: unless-stopped
