version: "3"

services:

  nzbget:
    image: linuxserver/nzbget
    volumes:
      - /dockerfs/nzbget/config:/config
      - /mnt/downloads:/downloads
    ports:
      - "6789:6789/tcp"
    environment:
      - 'TZ=America/New_York'
      - 'PUID=1001'
      - 'PGID=1001'
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == biggs
      labels:
        traefik.frontend.rule: 'Host:nzbget.desertbluffs.com'
        traefik.port: 6789
        traefik.docker.network: rc_default
      

  sonarr:
    image: linuxserver/sonarr
    volumes:
      - /dockerfs/sonarr/config:/config
      - /mnt/downloads:/downloads
      - /mnt/media:/media
      - /dev/rtc:/dev/rtc:ro 
    ports:
      - "8989:8989/tcp"
    environment:
      - 'PUID=1001'
      - 'PGID=1001'
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == biggs
      labels:
        traefik.frontend.rule: 'Host:sonarr.desertbluffs.com'
        traefik.port: 8989
        traefik.docker.network: rc_default

  couchpotato:
    image: linuxserver/couchpotato
    volumes:
      - /dockerfs/couchpotato/config:/config
      - /mnt/downloads:/downloads
      - /mnt/media/movies:/movies
    ports:
      - "5050:5050/tcp"
    environment:
      - 'PUID=1001'
      - 'PGID=1001'
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == biggs
      labels:
        traefik.frontend.rule: 'Host:couchpotato.desertbluffs.com'
        traefik.port: 5050
        traefik.docker.network: rc_default

  plexpy:
    image: linuxserver/plexpy
    volumes:
      - /dockerfs/plexpy/config:/config
      - '/dockerfs/pms/config/Library/Application Support/Plex Media Server/Logs/:/logs:ro'
    ports:
      - "8181:8181/tcp"
    environment:
      - 'PUID=1001'
      - 'PGID=1001'
      - 'TZ=America/New_York'
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == wedge
      labels:
        traefik.frontend.rule: 'Host:plexpy.desertbluffs.com'
        traefik.port: 8181
        traefik.docker.network: rc_default

  traefik:
    image: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dockerfs/traefik/config:/etc/traefik
      - /dockerfs/traefik/config/acme/acme.json:/acme.json
    ports:
      - "8080:8080/tcp"
      - "80:80/tcp"
      - "443:443/tcp"
    command: >-
      traefik
      --docker
      --docker.swarmmode
      --docker.domain=desertbluffs.com
      --docker.watch
      --web
      --debug
      --configfile=/etc/traefik/traefik.toml
    env_file:
      - env/private/aws
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
          - node.hostname==cecil
